### ISSUE TITLE
Can build module. But cannot use.

### ISSUE THREAD

**Issue by olig1905** [KurtPattyn/QtSocketIo#1]
I have built the module with:
   qmake
   make
   make install

However when I try to build my project using QSocketIo I receive alot of error messages in:

/usr/include/qt/QtSocketIo/qcallback.h:58: error: 'decltype' has not been declared
     template <typename Func> static char test(decltype(&Func::operator()));

Other errors include:
/usr/include/qt/QtSocketIo/qcallback.h:58: error: 'decltype' has not been declared
     template <typename Func> static char test(decltype(&Func::operator()));
                                               ^

/usr/include/qt/QtSocketIo/qcallback.h:70: error: '&' cannot appear in a constant-expression
     enum { argument_count = function_traits<decltype(&Function::operator())>::argument_count };
                                                                          ^

I also get alot of warnings relating to c++ 11 only features.

**Comment by KurtPattyn** [comment]
Did you add c++11 to your CONFIG parameter in the .pro file of the application?

**Comment by olig1905** [comment]
Hi Kurt,

No I didn't that would have solved it. I have however since gone for a
solution using just your QWebsockets. So that L's for that it is great.
Just need to cross compile QWebsockets now. Was being lazy and building on
device but websockets is too big for that.

Also sorry I posted that as an issue. I realise I should have just sent a
message.

Oli
